### ISSUE TITLE
Glitching

### ISSUE THREAD

**Issue by z3t0** [deathcap/voxel-outline#7]
This seems to glitch often, especially on trees?
![image](https://cloud.githubusercontent.com/assets/9000061/7103519/e36a0524-e067-11e4-8389-9a5ac73b436e.png)

**Comment by z3t0** [comment]
Off the cube.
![image](https://cloud.githubusercontent.com/assets/9000061/7103631/daf121ce-e06d-11e4-95f2-546fb813748a.png)

**Comment by z3t0** [comment]
It seems that the outline gets offsetted but it would be better if instead we slightly scaled the outline to be larger.
![image](https://cloud.githubusercontent.com/assets/9000061/7106899/9140b3c2-e10e-11e4-94fd-f01a040dd224.png)


Because this happens where the cube is off the block and in the first screenshot that becomes extremely problematic because it goes on the other side

**Comment by z3t0** [comment]
![image](https://cloud.githubusercontent.com/assets/9000061/7106919/60d7ef56-e10f-11e4-9d1a-6d47b1ec9846.png)
Another example.

Does the outline get rendered as a cube? Or can we make it larger?

**Comment by deathcap** [comment]
This looks like https://github.com/deathcap/voxel-outline/issues/6 but I thought I fixed that in voxel-outline 0.4.2. Are you using that version, if so what are the world x y z coordinates of the block being outlined? The outline is supposed to be rendered as a cube wireframe slightly larger than one voxel.

**Comment by z3t0** [comment]
I am using 0.4.2.
I managed to fix the offset by setting `epsilon` to 0, but that obviously causes it to fight with voxel-wireframe, so I am trying to figure that out.

**Comment by z3t0** [comment]
Actually I am using 0.4.2

**Comment by z3t0** [comment]
We should update the package.json in voxelmetaverse its quite out of date

**Comment by z3t0** [comment]
I'll try the new one

**Comment by z3t0** [comment]
@deathcap Thanks, updating fixed it!
